### ISSUE TITLE
[umbrella issue] Search

### ISSUE THREAD

**Issue by simoneb** [nearform/brokeneck#15]
There are multiple places in the app where searches can occur:

- [x] when listing users
  - [x] cognito
  - [x] auth0
  - [x] azure - buggy, see https://github.com/nearform/brokeneck/issues/28
- [ ] when listing groups
  - [x] cognito - seems unsupported, to be handled in #19 
  - [x] auth0
  - [x] azure - buggy, see https://github.com/nearform/brokeneck/issues/28
- [X] when, in the group page, adding users to the group
  - [x] cognito
  - [x] auth0
  - [x] azure - buggy, see https://github.com/nearform/brokeneck/issues/28 (seems to work because client side autocomplete only shows matching results, but server is returning everything)
- [ ] when, in the user page, adding the user to a group
  - [ ] cognito
  - [ ] auth0
  - [ ] azure

We should support all providers in the backend (Auth0, Azure, Cognito)

**Comment by simoneb** [comment]
Closing as we don't need search when listing groups in the user page, especially because it's not supported everywhere
